spring.application.name=finance-api
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_api
spring.datasource.username=oleksandr
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true